---
title: "lableaf_analysis_paper"
author: "Sami Saarenpää"
date: "10/19/2021"
output: html_document
---
# Laod the packages
```{r}
suppressPackageStartupMessages({
  library(STutility)
  library(dplyr)
  library(stringr)
})


  library(Seurat)
  library(harmony)
  library(gridExtra)
  library(pals)
  library(akima)
  library(readr)
  library(plotly)
  library(tibble)
  library(raster)


  library(magrittr)
  library(ggplot2)
  library(imager)
  library(Matrix)
  library(cowplot)
  require(data.table)
  library(magick)
  library(grid)
  library(SeuratObject)
  library(harmony)
  library(RColorBrewer)
  library(gprofiler2)
  library(spdep)
```


#Infotable & load the data
```{r, fig.width = 22, fig.height=18}

samples <- list.files(path = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/data/Arabidopsis_counts", pattern = ".tsv", recursive = FALSE, full.names = T)[6]


imgs <- list.files(path = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/imgs/", pattern = ".jpg", recursive = FALSE, full.names = T)[6]

spotfiles <- list.files(path = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/imgs/", pattern = ".tsv", recursive = FALSE, full.names = T)[6]

sample_id = "50pt-5016S_C2"
leaf = "P7.C6"
probe = "50pT--50-16S"

scaleVisium <- 1

infoTable <- data.frame(samples, 
                        spotfiles, 
                        imgs, 
                        scaleVisium, 
                        sample_id,
                        leaf,
                        probe,
                        stringsAsFactors = F)

lableaf062 <- InputFromTable(infotable = infoTable, 
                                 transpose = F, 
                                 platform = "Visium") 


```

#Bacteria
```{r}
bacteria <- list.files(path = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/bacteria_210615", pattern = "usearch_unique_vs_NT_Jan2021.UMI_filtered.genus.spatial_pos.txt", recursive = FALSE, full.names = T)[6]
OMNI06_bacteria <- c()
for (i in 1:length(bacteria)){
  OMNI06_bacteria[[i]] <- read.csv(bacteria[[i]], row.names=1, sep=";", header = F)
}

colnames(OMNI06_bacteria[[1]]) <-lapply(lapply(OMNI06_bacteria[[1]][1,], function(x) paste(x,'_1')), function(x) str_remove(x, " "))

for (i in  1:length(OMNI06_bacteria)){
  
  OMNI06_bacteria[[i]] <- OMNI06_bacteria[[i]][-1,]
}



brns <- unique(unlist(lapply(OMNI06_bacteria, rownames)))
bcns <- colnames(lableaf062)
bac_df <- data.frame(matrix(0, nrow = length(brns), ncol = length(bcns)))
rownames(bac_df) <- brns
colnames(bac_df) <- bcns
 for (i in c(1:length(OMNI06_bacteria))){
  bac_df[rownames(OMNI06_bacteria[[i]]), colnames(OMNI06_bacteria[[i]])] = OMNI06_bacteria[[i]]
}
rmoves <- setdiff(colnames(bac_df), colnames(lableaf062))
bac_df_filt <- bac_df[ , -which(names(bac_df) %in% rmoves)]
bac_df_filt[is.na(bac_df_filt)]<- 0
lableaf062[['BACTERIA']] <- CreateAssayObject(counts = bac_df_filt)
DefaultAssay(lableaf062) <- "BACTERIA"

#saveRDS(lableaf062, "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/210925_lableaf062.plant_bacteria.rds")
#lableaf062 <- readRDS("/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/210925_lableaf062.plant_bacteria.rds")
```
#Summed counts on different data modalities
```{r}
lableaf062$nCount_RNABAC <- lableaf062[["nCount_RNA"]] + lableaf062[["nCount_BACTERIA"]]
lableaf062$nFeature_RNABAC <- lableaf062[["nFeature_RNA"]] + lableaf062[["nFeature_BACTERIA"]]
```


##Filter low number spots and genes
```{r, fig.width= 8, fig.height=20}

cat("Number of spots after subsetting filter:", ncol(lableaf062), "\n")
DefaultAssay(lableaf062) <- "RNA"
cat("Number of host genes before subsetting filter:", nrow(lableaf062), "\n")
DefaultAssay(lableaf062) <- "BACTERIA"
cat("Number of bacterial genes before subsetting filter:", nrow(lableaf062), "\n")


lableaf062 <- SubsetSTData(lableaf062, expression = nCount_RNABAC >= 20)
lableaf062 <- SubsetSTData(lableaf062, expression = nFeature_RNABAC >= 10)

RNA_data<-GetAssayData(lableaf062, assay = "RNA")
#RNA_data[RNA_data  <= 1] <- 0 
RNA_data<- RNA_data[rowSums(RNA_data != 0) >0, ]
#write.csv(RNA_data, file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211111_lableaf5050_rawdata.csv")

lableaf062[['RNA']] <- CreateAssayObject(counts = RNA_data)

BAC_data<-GetAssayData(lableaf062, assay = "BACTERIA")
#BAC_data[BAC_data  <= 1] <- 0 
BAC_data<- BAC_data[rowSums(BAC_data != 0) >0, ]
lableaf062[['BACTERIA']] <- CreateAssayObject(counts = BAC_data)

cat("Number of spots after subsetting filter:", ncol(lableaf062), "\n")
DefaultAssay(lableaf062) <- "RNA"
cat("Number of host genes before subsetting filter:", nrow(lableaf062), "\n")
DefaultAssay(lableaf062) <- "BACTERIA"
cat("Number of bacterial genes before subsetting filter:", nrow(lableaf062), "\n")
```
#Visualisation
##Load images
```{r}
lableaf062 <- LoadImages(lableaf062, time.resolve = F, xdim = 800)
```
##Opacity change
```{r, fig.width= 16, fig.height=13}
st.object <- GetStaffli(lableaf062) # Colect Staffli object from Seurat object

# following part will modify the "raw" images
# If you want to change the opacity for "masked" or "processed" images you will need to specify this
st.object@rasterlists$raw <- lapply(st.object@rasterlists$raw, function(im) {
  im <- apply(im, 2, function(x) {
    scales::alpha(x, alpha = 0.75)
  })
  return(im)
})
lableaf062@tools$Staffli <- st.object

ImagePlot(lableaf062)

```

##PR1
```{r, fig.width = 10, fig.height=10}

lableaf062$PR1 <- log10(lableaf062@assays$RNA@counts["AT2G14610", ] +1) 


#tiff(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211018_lableaf5050_log10_PR1.tiff", width = 4000, height = 4000, res = 300)
plot <- FeatureOverlay(object = lableaf062,
               features = "nCount_RNA",
               #spots = rownames(subset(lableaf062[[]],lableaf062@assays$RNA@counts["AT2G14610",] >= 1)),
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)
#dev.off()

```

##Pseudomonas

```{r, fig.width = 10, fig.height=10}
DefaultAssay(lableaf062) <- "BACTERIA"
lableaf062$log.Pseudomonas <- log10(lableaf062@assays$BACTERIA@counts["Pseudomonas", ] +1) 


#tiff(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211018_lableaf5050_log10_Pseudomonas.tiff", width = 4000, height = 4000, res = 300)
plot <- FeatureOverlay(object = lableaf062,
               features = "log.Pseudomonas",
               spots = rownames(subset(lableaf062[[]],lableaf062@assays$BACTERIA@counts["Pseudomonas",] >= 1)),
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)
#dev.off()

```
##All data modalities
###RNABAC nCount
```{r, fig.width = 10, fig.height=10}
DefaultAssay(lableaf062) <- "BACTERIA"
lableaf062$log.nCount_RNABAC <- log10(lableaf062[["nCount_RNABAC"]] +1) 


#tiff(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211018_lableaf5050_log10_nCount_RNABAC.tiff", width = 4000, height = 4000, res = 300)
plot <- FeatureOverlay(object = lableaf062,
               features = "log.nCount_RNABAC",
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)
#dev.off()


```


###RNABAC nFeature
```{r, fig.width = 10, fig.height=10}
DefaultAssay(lableaf062) <- "BACTERIA"
lableaf062$log.nFeature_RNABAC <- log10(lableaf062[["nFeature_RNABAC"]] +1) 


#tiff(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211018_lableaf5050_log10_nFeature_RNABAC.tiff", width = 4000, height = 4000, res = 300)
plot <- FeatureOverlay(object = lableaf062,
               features = "log.nFeature_RNABAC",
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)
#dev.off()
```
###RNA nCount
```{r, fig.width = 10, fig.height=10}
DefaultAssay(lableaf062) <- "RNA"
lableaf062$log.nCount_RNA <- log10(lableaf062[["nCount_RNA"]] +1) 
lableaf062$log.nFeature_RNA <- log10(lableaf062[["nFeature_RNA"]] +1)


#pdf(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211111_lableaf5050_nCount_RNA.pdf", useDingbats = F,width = 4, height = 4)
plot <- FeatureOverlay(object = lableaf062,
               features = "nCount_RNA",
               pt.size = 0.8,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 0.9)

print(plot)
#dev.off()


#pdf(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211111_lableaf5050_nFeature_RNA.pdf", useDingbats = F,width = 4, height = 4)
plot <- FeatureOverlay(object = lableaf062,
               features = "nFeature_RNA",
               pt.size = 0.8,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 0.9)

print(plot)
#dev.off()

#pdf(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211111_lableaf5050_log_nCount_RNA.pdf", useDingbats = F,width = 4, height = 4)
plot <- FeatureOverlay(object = lableaf062,
               features = "log.nCount_RNA",
               pt.size = 0.8,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 0.9)

print(plot)
#dev.off()

#pdf(file = "/home/st-analysis_home/sami.saarenpaa/runs/Arabidopsis/201002_191028-062/R_analysis/211111_lableaf5050_log_nFeature_RNA.pdf", useDingbats = F,width = 4, height = 4)
plot <- FeatureOverlay(object = lableaf062,
               features = "log.nFeature_RNA",
               pt.size = 0.8,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 0.9)

print(plot)
#dev.off()

```
#Stats from section 6
```{r}

DefaultAssay(lableaf062) <- "RNA"
keep.host <- rownames(lableaf062[rowSums(lableaf062) >20,])

cat(sprintf("Number of genes in host (filtered): %s", length(keep.host)))


DefaultAssay(lableaf062) <- "BACTERIA"
keep.bacteria <- rownames(lableaf062[rowSums(lableaf062) >10,])
cat(sprintf("\nNumber of bacterial taxa (filtered): %s", length(keep.bacteria)))



DefaultAssay(lableaf062) <- "RNA"
ff <- as.numeric(rowSums(lableaf062[rowSums(lableaf062) >20,]))

cat(sprintf("\nNumber of unique Arabidopsis molecules (filtered): %s", Reduce(`+`, ff)))


DefaultAssay(lableaf062) <- "BACTERIA"
fb <- as.numeric(rowSums(lableaf062[rowSums(lableaf062) >10,]))
cat(sprintf("\nNumber of unique bacterial molecules (filtered): %s", Reduce(`+`, fb)))


```


                                  