---
title: "lableaf_analysis_paper"
author: "Sami Saarenpää"
date: "10/19/2021"
output: html_document
---
# Laod the packages
```{r}
suppressPackageStartupMessages({
  library(STutility)
  library(dplyr)
  library(stringr)
  library(corrplot)
  library(cowplot) 
  library(ggpubr)
  library(tidyr)

})

```


#Infotable & load the data
```{r, fig.width = 22, fig.height=18}

samples <- list.files(path = "Arabidopsis/201002_191028-062/data/Arabidopsis_counts", pattern = ".tsv", recursive = FALSE, full.names = T)[6]


imgs <- list.files(path = "Arabidopsis/201002_191028-062/imgs/", pattern = ".jpg", recursive = FALSE, full.names = T)[6]

spotfiles <- list.files(path = "Arabidopsis/201002_191028-062/imgs/", pattern = ".tsv", recursive = FALSE, full.names = T)[6]

spots <- read.csv("Arabidopsis/201002_191028-062/imgs/EXP6_Arabidopsis_C2_alignment.tsv", sep = "\t")
spots$coordinates <- paste(spots$x, "x", spots$y)
length(unique(spots$coordinates))

sample_id = "50pt-5016S_C2"
leaf = "P7.C6"
probe = "50pT--50-16S"

scaleVisium <- 1

infoTable <- data.frame(samples, 
                        spotfiles, 
                        imgs, 
                        scaleVisium, 
                        sample_id,
                        leaf,
                        probe,
                        stringsAsFactors = F)

lableaf062 <- InputFromTable(infotable = infoTable, 
                                 transpose = F, 
                                 platform = "Visium")



```

#Bacteria
```{r}
bacteria <- list.files(path = "Arabidopsis/201002_191028-062/bacteria_210615", pattern = "usearch_unique_vs_NT_Jan2021.UMI_filtered.genus.spatial_pos.txt", recursive = FALSE, full.names = T)[6]
EXP06_bacteria <- c()
for (i in 1:length(bacteria)){
  EXP06_bacteria[[i]] <- read.csv(bacteria[[i]], row.names=1, sep=";", header = F)
}

colnames(EXP06_bacteria[[1]]) <-lapply(lapply(EXP06_bacteria[[1]][1,], function(x) paste(x,'_1')), function(x) str_remove(x, " "))

for (i in  1:length(EXP06_bacteria)){
  
  EXP06_bacteria[[i]] <- EXP06_bacteria[[i]][-1,]
}



brns <- unique(unlist(lapply(EXP06_bacteria, rownames)))
bcns <- colnames(lableaf062)
bac_df <- data.frame(matrix(0, nrow = length(brns), ncol = length(bcns)))
rownames(bac_df) <- brns
colnames(bac_df) <- bcns
 for (i in c(1:length(EXP06_bacteria))){
  bac_df[rownames(EXP06_bacteria[[i]]), colnames(EXP06_bacteria[[i]])] = EXP06_bacteria[[i]]
}
rmoves <- setdiff(colnames(bac_df), colnames(lableaf062))
bac_df_filt <- bac_df[ , -which(names(bac_df) %in% rmoves)]
bac_df_filt[is.na(bac_df_filt)]<- 0
bac_df_filt <- as.data.frame(sapply(bac_df_filt, as.numeric))
rownames(bac_df_filt) <- rownames(bac_df) 


lableaf062[['BACTERIA']] <- CreateAssayObject(counts = bac_df_filt)
DefaultAssay(lableaf062) <- "BACTERIA"

```
#Summed counts on different data modalities
```{r}
lableaf062$nCount_RNABAC <- lableaf062[["nCount_RNA"]] + lableaf062[["nCount_BACTERIA"]]
lableaf062$nFeature_RNABAC <- lableaf062[["nFeature_RNA"]] + lableaf062[["nFeature_BACTERIA"]]
```


##Filter low number spots and genes
```{r, fig.width= 8, fig.height=20}

lableaf062 <- SubsetSTData(lableaf062, expression = nCount_RNABAC >= 20)
lableaf062 <- SubsetSTData(lableaf062, expression = nFeature_RNABAC >= 10)

RNA_data<-GetAssayData(lableaf062, assay = "RNA")
RNA_data<- RNA_data[rowSums(RNA_data != 0) >0, ]

lableaf062[['RNA']] <- CreateAssayObject(counts = RNA_data)

BAC_data<-GetAssayData(lableaf062, assay = "BACTERIA")
BAC_data<- BAC_data[rowSums(BAC_data != 0) >0, ]
lableaf062[['BACTERIA']] <- CreateAssayObject(counts = BAC_data)

```
#Visualisation
##Load images
```{r}
lableaf062 <- LoadImages(lableaf062, time.resolve = F, xdim = 800)
```
##Opacity change
```{r, fig.width= 16, fig.height=13}
st.object <- GetStaffli(lableaf062) # Colect Staffli object from Seurat object

# following part will modify the "raw" images
# If you want to change the opacity for "masked" or "processed" images you will need to specify this
st.object@rasterlists$raw <- lapply(st.object@rasterlists$raw, function(im) {
  im <- apply(im, 2, function(x) {
    scales::alpha(x, alpha = 0.75)
  })
  return(im)
})
lableaf062@tools$Staffli <- st.object

ImagePlot(lableaf062)

```

#FL information
```{r, fig.width = 10, fig.height=8}
FL <- read.csv(file = "Arabidopsis/revision/fl_experiment/230308_Arabidopsis_fluorescent_fixed_border_new.tsv", sep = "\t")

FL$coordinates <- paste(FL$x, "x", FL$y)
FL$coordinates <- paste(FL$coordinates, "_1")

FL <- FL %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

rownames(FL) <- FL$coordinates

FL <- FL[,-c(4)]
FL <- FL[,-c(1:2)]
FL <- as.data.frame(t(FL))
FL <- FL[-c(2),]


keep.spots <- colnames(lableaf062)
FL<- FL[,keep.spots]


lableaf062[['Fluorescent']] <- CreateAssayObject(counts = FL)
DefaultAssay(lableaf062) <- "Fluorescent"

lableaf062$FLmax <- lableaf062@assays$Fluorescent@counts["max", ]
lableaf062$PR1 <- lableaf062@assays$RNA@counts["AT2G14610", ]


FeatureOverlay(object = lableaf062,
               features = "max",
               pt.size = 4,
               type = "raw",
               show.sb = T,
               palette = "Reds",
               value.scale = c("samplewise"),
               pt.alpha = 1)

#spots for the Eulerr plots
Ps_spots<- rownames(subset(lableaf062[[]],lableaf062@assays$BACTERIA@counts["Pseudomonas",] >= 1))
#write.csv(Ps_spots, "Arabidopsis/revision/fl_experiment/230311_venn_Pseudomonas.csv")
PR1_spots<- rownames(subset(lableaf062[[]],lableaf062@assays$RNA@counts["AT2G14610",] >= 1))
#write.csv(PR1_spots, "Arabidopsis/revision/fl_experiment/230311_venn_PR1.csv")
FLmax_spots <- rownames(subset(lableaf062[[]],lableaf062@assays$Fluorescent@counts["max",] >= 45))
#write.csv(FLmax_spots, "Arabidopsis/revision/fl_experiment/230311_venn_FLmax.csv")

df <- data.frame(pseudomonas = ifelse(lableaf062@assays$BACTERIA@counts["Pseudomonas", ] >= 1, "Pseudomonas", ""),
                 PR1 = ifelse(lableaf062@assays$RNA@counts["AT2G14610", ] >= 1, "PR1", ""),
                 FL = ifelse(lableaf062@assays$Fluorescent@counts["max", ] >= 45, "FL", ""))
df <- df %>% 
  as_tibble() %>% 
  unite("category", everything(), sep = "") %>% 
  mutate(category = factor(category))

lableaf062$category <- df$category

FeatureOverlay(lableaf062, features = "category", spots = rownames(subset(lableaf062[[]],lableaf062$category == "FL")), pt.size = 2.5, cols  = c("#fffce8", "#B8B42D", "blue", "pink", "green", "darkred", "lightblue" ))


FeatureOverlay(lableaf062, features = "category", spots = rownames(subset(lableaf062[[]],lableaf062$category == "PseudomonasPR1FL")), pt.size = 2.5, cols  = c("#fffce8", "#B8B42D", "blue", "pink", "green", "darkred", "lightblue" ))

```

#Correlation
```{r, fig.width = 10, fig.height=10}
se.subset <- SubsetSTData(lableaf062, expression = FLmax >= 45 )

maxFL <- log10(lableaf062@assays$Fluorescent@counts["max",] +1)
Pseudom <- log10(lableaf062@assays$BACTERIA@counts["Pseudomonas",]+1) 
PR1 <- log10(lableaf062@assays$RNA@counts["AT2G14610",]+1) 


corData <- data.frame(maxFL, Pseudom, PR1)


ggplot(corData, aes(y=Pseudom, x=PR1)) +
  geom_point(size=0.5, shape=23) +
  geom_smooth(method="lm", se=TRUE, fullrange=FALSE, level=0.95, linetype="dashed",color="darkred") + 
  stat_cor( method="pearson", label.x =1, label.y=3.5)


ggplot(corData, aes(y=Pseudom, x=maxFL)) +
  geom_point(size=0.5, shape=23) +
  geom_smooth(method="lm", se=TRUE, fullrange=FALSE, level=0.95, linetype="dashed",color="darkred") + 
  stat_cor( method="pearson")  +
  xlab("log10(Maximum fluorescent values - Pseudomonas + 1)") + ylab("log10(Captured Pseudomonas +1)")

```
##PR1
```{r, fig.width = 10, fig.height=10}

lableaf062$PR1 <- log10(lableaf062@assays$RNA@counts["AT2G14610", ] +1) 

plot <- FeatureOverlay(object = lableaf062,
               features = "PR1",
               spots = rownames(subset(lableaf062[[]],lableaf062@assays$RNA@counts["AT2G14610",] >= 1)),
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)


```

##Pseudomonas

```{r, fig.width = 10, fig.height=10}
DefaultAssay(lableaf062) <- "BACTERIA"
lableaf062$log.Pseudomonas <- log10(lableaf062@assays$BACTERIA@counts["Pseudomonas", ] +1) 
sum(lableaf062@assays$BACTERIA@counts["Pseudomonas", ])

plot <- FeatureOverlay(object = lableaf062,
               features = "Pseudomonas",
               spots = rownames(subset(lableaf062[[]],lableaf062@assays$BACTERIA@counts["Pseudomonas",] >= 1)),
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)


```
##All data modalities
###RNABAC nCount
```{r, fig.width = 10, fig.height=10}
DefaultAssay(lableaf062) <- "BACTERIA"
lableaf062$log.nCount_RNABAC <- log10(lableaf062[["nCount_RNABAC"]] +1) 

plot <- FeatureOverlay(object = lableaf062,
               features = "log.nCount_RNABAC",
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)

```


###RNABAC nFeature
```{r, fig.width = 10, fig.height=10}
DefaultAssay(lableaf062) <- "BACTERIA"
lableaf062$log.nFeature_RNABAC <- log10(lableaf062[["nFeature_RNABAC"]] +1) 

plot <- FeatureOverlay(object = lableaf062,
               features = "log.nFeature_RNABAC",
               pt.size = 2.5,
               type = "raw",
               show.sb = T,
               value.scale = c("samplewise"),
               cols =  c("#fffce8", "#B8B42D", "#B8B42D", "3e363f", "3e363f", "697a21", "697a21"),
               pt.alpha = 1)

print(plot)

```

#Stats from the section 
```{r}

DefaultAssay(lableaf062) <- "RNA"
keep.host <- rownames(lableaf062[rowSums(lableaf062) >20,])

cat(sprintf("Number of genes in host (filtered): %s", length(keep.host)))


DefaultAssay(lableaf062) <- "BACTERIA"
keep.bacteria <- rownames(lableaf062[rowSums(lableaf062) >10,])
cat(sprintf("\nNumber of bacterial taxa (filtered): %s", length(keep.bacteria)))



DefaultAssay(lableaf062) <- "RNA"
ff <- as.numeric(rowSums(lableaf062[rowSums(lableaf062) >20,]))

cat(sprintf("\nNumber of unique Arabidopsis molecules (filtered): %s", Reduce(`+`, ff)))


DefaultAssay(lableaf062) <- "BACTERIA"
fb <- as.numeric(rowSums(lableaf062[rowSums(lableaf062) >10,]))
cat(sprintf("\nNumber of unique bacterial molecules (filtered): %s", Reduce(`+`, fb)))


```
                                  